version: '3'
services:
   opsmanager:
     image: ksravikumar2005/opsmanager:latest
     hostname: opsmanager 
     ports:
       - 18080:8080
       - 18081:8081
     volumes:
       - etc-mms:/etc/mongodb-mms
       - opt-mms:/opt/mongodb/mms
     networks:
       - opsmanager
#     deploy:
#       placement:
#         constraints:
#           - node.labels.name == <your node label>
#       replicas: 1

volumes:
   etc-mms:
   opt-mms:
networks:
  opsmanager:
