version: '3'
services:
   node1:
    hostname: node1
    image: ksravikumar2005/mongodb-automation-agent:latest 
    ports:
      - 11117:27000
    volumes:
      - automation-agent-datadb:/data/db
    networks:
      - opsmanager
    command: --mmsBaseUrl=http://2886795309-18080-frugo01.environments.katacoda.com --mmsGroupId=5dafc4d4a228fe006323ae1c  --mmsApiKey=5dafc550a228fe006323ae60fa9207dd7a9697c509d7cd99b2852f1f
volumes:
   automation-agent-datadb:
networks:
 opsmanager:

