version: '3'
services:
   opsmanager:
     build: ./ops-manager
     ports:
       - 8080:8080
       - 8081:8081
     volumes:
       - opsmanager_datadb:/data/db
       - etc-mms:/etc/mongodb-mms
       - opt-mms:/opt/mongodb/mms
     networks:
       - opsmanager

   db:
     image: mongo:latest
     ports:
       - 27017:27017
     volumes:
       - opsmanagerdatabase_datadb:/data/db
     networks:
       - opsmanager
   backup:
     image: mongo:latest
     ports:
       - 37017:27017
     volumes:
       - backupdatabase_datadb:/data/db
     networks:
       - opsmanager
   node1:
     image: ksravikumar2005/mongo:automation-agent-centos-root
     hostname: node1
     command: --mmsBaseUrl=http://192.168.0.28:8080 --mmsGroupId=5bdefd53857aba0079615365  --mmsApiKey=5bdeff82857aba00796153980d37960bfe8405b6799e89e68e269d73  --logFile=/var/log/mongodb-mms-automation/automation-agent.log
     ports:
       - 47017:27017
     volumes:
       - node1_datadb:/data/db
       - ./certs:/certs
     networks:
       - opsmanager




volumes:
   opsmanager_datadb:
   etc-mms:
   opsmanagerdatabase_datadb:
   opt-mms:
   backupdatabase_datadb:
networks:
  opsmanager:

